linters:
  Comment:
    enabled: false
  HexLength:
    style: "long"
  HexNotation:
    style: "uppercase"
  IdSelector:
    enabled: false
  ImportantRule:  # While I agree with this one, we do need to use !important in some cases
    enabled: false
  NameFormat:
    convention: "snake_case"
  NestingDepth:
    max_depth: 4
  SelectorDepth:
    max_depth: 4
  StringQuotes:
    style: "double_quotes"
