# Generated by Django 2.2.13 on 2020-06-19 19:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.CharField(help_text='The unique ID used in the sharing link for the form', max_length=60, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(help_text='The title of the form as displayed in the header section')),
                ('public', models.BooleanField(default=False, help_text='Whether this form should be publicly accessible')),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField(help_text='The questions on the form in JSON format')),
            ],
        ),
    ]
