# Generated by Django 2.2.13 on 2020-06-20 02:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The questions on the form in JSON format'),
        ),
    ]
