# Generated by Django 2.2.13 on 2020-06-20 16:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_add_requires_oauth2_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, editable=False, help_text='The questions on the form in JSON format'),
        ),
    ]
