# Generated by Django 2.1 on 2018-08-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationLink',
            fields=[
                ('package', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('base_url', models.URLField()),
                ('inventory_url', models.URLField()),
            ],
        ),
    ]
