# Generated by Django 2.1.1 on 2018-09-21 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationlink',
            name='base_url',
            field=models.URLField(help_text='The base URL from which documentation will be available for this project. Used to generate links to various symbols within this package.'),
        ),
        migrations.AlterField(
            model_name='documentationlink',
            name='inventory_url',
            field=models.URLField(help_text='The URL at which the Sphinx inventory is available for this package.'),
        ),
        migrations.AlterField(
            model_name='documentationlink',
            name='package',
            field=models.CharField(help_text='The Python package name that this documentation link belongs to.', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offtopicchannelname',
            name='name',
            field=models.CharField(help_text='The actual channel name that will be used on our Discord server.', max_length=96, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='snakename',
            name='name',
            field=models.CharField(help_text="The regular name for this snake, e.g. 'Python'.", max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='snakename',
            name='scientific',
            field=models.CharField(help_text="The scientific name for this snake, e.g. 'Python bivittatus'.", max_length=150),
        ),
    ]
