# Generated by Django 2.1.1 on 2018-09-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tag'),
    ]

    operations = [
    ]
