# Generated by Django 2.1.2 on 2018-10-23 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_specialsnake'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialsnake',
            name='image',
            field=models.URLField(default=datetime.datetime(2018, 10, 23, 11, 51, 23, 703868, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
