# Generated by Django 2.1.2 on 2018-10-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_specialsnake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsnake',
            name='info',
            field=models.TextField(help_text='Info about a special snake.'),
        ),
        migrations.AlterField(
            model_name='specialsnake',
            name='name',
            field=models.CharField(help_text='A special snake name.', max_length=140, primary_key=True, serialize=False),
        ),
    ]
