# Generated by Django 2.1.2 on 2018-10-27 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181025_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsnake',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
    ]
