# Generated by Django 2.1.3 on 2018-11-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_guild',
            field=models.BooleanField(default=True, help_text='Whether this user is in our server.'),
        ),
    ]
