# Generated by Django 2.1.2 on 2018-11-24 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_in_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakename',
            name='name',
            field=models.CharField(help_text="The regular name for this snake, e.g. 'Python'.", max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^([^0-9])+$')]),
        ),
        migrations.AlterField(
            model_name='snakename',
            name='scientific',
            field=models.CharField(help_text="The scientific name for this snake, e.g. 'Python bivittatus'.", max_length=150, validators=[django.core.validators.RegexValidator(regex='^([^0-9])+$')]),
        ),
    ]
