# Generated by Django 2.1.3 on 2018-11-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_infraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='reason',
            field=models.TextField(help_text='The reason for the infraction.', null=True),
        ),
    ]
