# Generated by Django 2.1.3 on 2018-11-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_infraction_remove_note'),
        ('api', '0021_add_special_snake_validator'),
    ]

    operations = [
    ]
