# Generated by Django 2.1.4 on 2019-01-06 16:01

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_note_infraction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='inserted_at',
            field=models.DateTimeField(default=timezone.now, help_text='The date and time of the creation of this infraction.'),
        ),
    ]
