# Generated by Django 2.1.5 on 2019-01-27 11:01

import pydis_site.apps.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('active', models.BooleanField(default=True, help_text='Whether this nomination is still relevant.')),
                ('reason', models.TextField(help_text='Why this user was nominated.')),
                ('user', models.OneToOneField(help_text='The nominated user.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nomination', serialize=False, to='api.User')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, help_text='The creation date of this nomination.')),
                ('author', models.ForeignKey(help_text='The staff member that nominated this user.', on_delete=django.db.models.deletion.CASCADE, related_name='nomination_set', to='api.User')),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
    ]
