# Generated by Django 2.1.5 on 2019-02-18 19:41

import pydis_site.apps.api.models.bot.bot_setting
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_create_defcon_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsetting',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[
                pydis_site.apps.api.models.bot.bot_setting.validate_bot_setting_name]),
        ),
    ]
