# Generated by Django 2.2.3 on 2019-07-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_create_table_log_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnakeFact',
        ),
        migrations.DeleteModel(
            name='SnakeIdiom',
        ),
        migrations.DeleteModel(
            name='SnakeName',
        ),
        migrations.DeleteModel(
            name='SpecialSnake',
        ),
    ]
