# Generated by Django 2.2.3 on 2019-07-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_nomination_field_name_change'),
        ('api', '0036_removing_snake_apis'),
    ]

    operations = [
    ]
