# Generated by Django 2.2.3 on 2019-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20190719_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='position',
            field=models.IntegerField(default=-1, help_text='The position of the role in the role hierarchy of the Discord Guild.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.IntegerField(help_text='The position of the role in the role hierarchy of the Discord Guild.'),
        )
    ]
