# Generated by Django 2.2.3 on 2019-09-03 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_add_position_field_to_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offtopicchannelname',
            name='name',
            field=models.CharField(help_text='The actual channel name that will be used on our Discord server.', max_length=96, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex="^[a-z0-9\\U0001d5a0-\\U0001d5b9-ǃ？’']+$")]),
        ),
    ]
