# Generated by Django 2.2.3 on 2019-09-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_allow_special_off_topic_name_chars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedmessage',
            options={'ordering': ['id']},
        ),
    ]
