# Generated by Django 2.2.3 on 2019-09-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_add_default_ordering_deleted_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraction',
            options={'ordering': ['-inserted_at']},
        ),
    ]
