# Generated by Django 2.2.3 on 2019-10-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_infraction_hidden_warnings_to_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name_plural': 'Log entries'},
        ),
    ]
