# Generated by Django 2.2.6 on 2019-10-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_add_plural_name_for_log_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='jump_url',
            field=models.URLField(default='', help_text='The jump url to the message that created the reminder', max_length=88),
            preserve_default=False,
        ),
    ]
