# Generated by Django 2.2.6 on 2019-10-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_reminder_jump_url'),
        ('api', '0046_offensivemessage'),
    ]

    operations = [
    ]
