# Generated by Django 2.2.6 on 2019-10-25 17:21

from django.db import migrations, models
import pydis_site.apps.api.models.bot.offensive_message


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_merge_20191025_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offensivemessage',
            name='delete_date',
            field=models.DateTimeField(help_text='The date on which the message will be auto-deleted.', validators=[pydis_site.apps.api.models.bot.offensive_message.future_date_validator]),
        ),
    ]
