# Generated by Django 2.2.6 on 2019-11-07 18:08

import django.core.validators
from django.db import migrations, models
import pydis_site.apps.api.models.bot.offensive_message
import pydis_site.apps.api.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_add_infractions_unique_constraints_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffensiveMessage',
            fields=[
                ('id', models.BigIntegerField(help_text='The message ID as taken from Discord.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Message IDs cannot be negative.')])),
                ('channel_id', models.BigIntegerField(help_text='The channel ID that the message was sent in, taken from Discord.', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Channel IDs cannot be negative.')])),
                ('delete_date', models.DateTimeField(help_text='The date on which the message will be auto-deleted.', validators=[pydis_site.apps.api.models.bot.offensive_message.future_date_validator])),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
    ]
