# Generated by Django 2.2.6 on 2019-12-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_offensivemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='active',
            field=models.BooleanField(help_text='Whether the infraction is still active.'),
        ),
    ]
