# Generated by Django 2.2.6 on 2020-02-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_deletedmessage_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='active',
            field=models.BooleanField(help_text='Whether the infraction is still active.'),
        ),
    ]
