# Generated by Django 3.0.4 on 2020-03-21 17:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import pydis_site.apps.api.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_infractions_active_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedmessage',
            name='embeds',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(validators=[pydis_site.apps.api.models.utils.validate_embed]), blank=True, help_text='Embeds attached to this message.', size=None),
        ),
    ]
