# Generated by Django 2.2.11 on 2020-04-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_infractions_active_default_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
