# Generated by Django 2.2.11 on 2020-05-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_create_news_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_hash',
        ),
    ]
