# Generated by Django 2.2.8 on 2020-01-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_deletedmessage_attachments'),
        ('api', '0052_add_whitelist_unique_constraint'),
    ]

    operations = [
    ]
