# Generated by Django 2.2.14 on 2020-07-15 07:37

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_user_invalidate_unknown_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='mentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Mention IDs cannot be negative.')]), blank=True, default=list, help_text='IDs of roles or users to ping with the reminder.', size=None),
        ),
    ]
