# Generated by Django 3.0.8 on 2020-07-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_allow_blank_message_embeds'),
        ('api', '0054_user_invalidate_unknown_role'),
    ]

    operations = [
    ]
