# Generated by Django 3.0.8 on 2020-07-14 20:35

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import pydis_site.apps.api.models.bot.user


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_merge_20200714_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Role IDs cannot be negative.'), pydis_site.apps.api.models.bot.user._validate_existing_role]), blank=True, default=list, help_text='IDs of roles the user has on the server', size=None),
        ),
    ]
