# Generated by Django 2.2.14 on 2020-07-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_reminder_mentions'),
        ('api', '0056_allow_blank_user_roles'),
    ]

    operations = [
    ]
