# Generated by Django 3.0.8 on 2020-07-15 11:23

from django.db import migrations, models
import pydis_site.apps.api.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0056_allow_blank_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowDenyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(
                    choices=[('GUILD_INVITE_ID', 'Guild Invite Id'), ('FILE_FORMAT', 'File Format'),
                             ('DOMAIN_NAME', 'Domain Name'), ('WORD_WATCHLIST', 'Word Watchlist')],
                    help_text='The type of allowlist this is on.', max_length=50)),
                ('allowed', models.BooleanField(help_text='Whether this item is on the allowlist or the denylist.')),
                ('content', models.TextField(help_text='The data to add to the allow or denylist.')),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='allowdenylist',
            constraint=models.UniqueConstraint(fields=('content', 'type'), name='unique_allow_deny_list'),
        )
    ]
