# Generated by Django 3.0.8 on 2020-08-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_populate_filterlists_fix'),
        ('api', '0052_offtopicchannelname_used'),
    ]

    operations = [
    ]
