# Generated by Django 3.0.8 on 2020-08-04 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_populate_filterlists_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationlink',
            name='package',
            field=models.CharField(help_text='The Python package name that this documentation link belongs to.', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Package names can only consist of lowercase a-z letters, digits, and underscores.', regex='^[a-z0-9_]+$')]),
        ),
    ]
