# Generated by Django 3.0.8 on 2020-09-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_delete_tag'),
        ('api', '0061_merge_20200830_0526'),
    ]

    operations = [
    ]
