# Generated by Django 3.0.9 on 2020-09-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_20200901_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='reason',
            field=models.TextField(blank=True, help_text='Why this user was nominated.', null=True),
        ),
    ]
