# Generated by Django 3.0.9 on 2020-09-19 19:00

import django.core.validators
from django.db import migrations, models
import pydis_site.apps.api.models.bot.offensive_message


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_Allow_blank_or_null_for_nomination_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedmessage',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='messagedeletioncontext',
            options={'ordering': ('-creation',)},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'ordering': ('-inserted_at',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('-position',)},
        ),
        migrations.AlterField(
            model_name='deletedmessage',
            name='channel_id',
            field=models.BigIntegerField(help_text='The channel ID that this message was sent in, taken from Discord.', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Channel IDs cannot be negative.')], verbose_name='Channel ID'),
        ),
        migrations.AlterField(
            model_name='deletedmessage',
            name='id',
            field=models.BigIntegerField(help_text='The message ID as taken from Discord.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Message IDs cannot be negative.')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='end_reason',
            field=models.TextField(blank=True, default='', help_text='Why the nomination was ended.'),
        ),
        migrations.AlterField(
            model_name='offensivemessage',
            name='channel_id',
            field=models.BigIntegerField(help_text='The channel ID that the message was sent in, taken from Discord.', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Channel IDs cannot be negative.')], verbose_name='Channel ID'),
        ),
        migrations.AlterField(
            model_name='offensivemessage',
            name='delete_date',
            field=models.DateTimeField(help_text='The date on which the message will be auto-deleted.', validators=[pydis_site.apps.api.models.bot.offensive_message.future_date_validator], verbose_name='To Be Deleted'),
        ),
        migrations.AlterField(
            model_name='offensivemessage',
            name='id',
            field=models.BigIntegerField(help_text='The message ID as taken from Discord.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Message IDs cannot be negative.')], verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigIntegerField(help_text='The role ID, taken from Discord.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Role IDs cannot be negative.')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(help_text='The ID of this user, taken from Discord.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='User IDs cannot be negative.')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_guild',
            field=models.BooleanField(default=True, help_text='Whether this user is in our server.', verbose_name='In Guild'),
        ),
    ]
