# Generated by Django 3.0.9 on 2020-09-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200919_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationlink',
            options={'ordering': ['package']},
        ),
    ]
