# Generated by Django 3.0.9 on 2020-10-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_delete_logentry'),
        ('api', '0065_auto_20200919_2033'),
    ]

    operations = [
    ]
