# Generated by Django 3.0.9 on 2020-10-26 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pydis_site.apps.api.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_voice_ban_infraction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('name', models.CharField(help_text='Name of the user event.', max_length=64, primary_key=True, serialize=False, verbose_name='Event Name')),
                ('description', models.TextField()),
                ('message_id', models.BigIntegerField(help_text='The message ID of the message sent in user events channel.', unique=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='message IDs cannot be negative.')])),
                ('organizer', models.ForeignKey(help_text='The event organizer.', on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscriptions', to='api.User')),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField(unique=True)),
                ('user_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserEvent')),
            ],
        ),
    ]
