# Generated by Django 3.0.9 on 2020-10-11 04:56

from django.db import migrations, models
import django.db.models.deletion
import pydis_site.apps.api.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_voice_ban_infraction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the user event.', max_length=128, unique=True, verbose_name='Event Name')),
                ('description', models.TextField(blank=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscriptions', to='api.User')),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
    ]
