# Generated by Django 3.0.11 on 2021-02-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_split_nomination_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominationentry',
            options={'verbose_name_plural': 'nomination entries'},
        ),
    ]
