# Generated by Django 3.0.9 on 2020-11-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_scheduledevent_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='end_time',
            field=models.DateTimeField(help_text='The end time of the scheduled user event.', unique=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='start_time',
            field=models.DateTimeField(help_text='The start time of the scheduled user event.', unique=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='user_event',
            field=models.OneToOneField(help_text='The user event which is scheduled.', on_delete=django.db.models.deletion.CASCADE, to='api.UserEvent'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, help_text="List of discord user id's how those who have subscribed to this event.", related_name='subscriptions', to='api.User'),
        ),
    ]
