# Generated by Django 3.0.14 on 2021-05-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_documentationlink_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='offtopicchannelname',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether or not this name should be considered for naming channels.'),
        ),
        migrations.AlterField(
            model_name='offtopicchannelname',
            name='used',
            field=models.BooleanField(default=False, help_text='Whether or not this name has already been used during this rotation.'),
        ),
    ]
