# Generated by Django 3.0.14 on 2021-06-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_documentationlink_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedmessage',
            name='content',
            field=models.CharField(blank=True, help_text='The content of this message, taken from Discord.', max_length=4000),
        ),
    ]
