# Generated by Django 3.0.9 on 2020-11-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20201104_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='subscriptions',
        ),
    ]
