# Generated by Django 3.0.14 on 2021-07-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_increase_message_content_4000'),
        ('api', '0070_auto_20210519_0545'),
    ]

    operations = [
    ]
