# Generated by Django 3.0.14 on 2021-08-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_increase_message_content_4000'),
        ('api', '0070_remove_userevent_subscriptions'),
    ]

    operations = [
    ]
