# Generated by Django 3.0.14 on 2021-10-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_otn_allow_GT_and_LT'),
        ('api', '0070_new_filter_schema'),
    ]

    operations = [
    ]
