# Generated by Django 3.0.14 on 2021-11-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_merge_20210724_1354'),
        ('api', '0073_otn_allow_GT_and_LT'),
    ]

    operations = [
    ]
