# Generated by Django 3.0.14 on 2021-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_otn_allow_GT_and_LT'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='failures',
            field=models.IntegerField(default=0, help_text='Number of times we attempted to send the reminder and failed.'),
        ),
    ]
