# Generated by Django 3.0.14 on 2021-11-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_reminder_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='dm_sent',
            field=models.BooleanField(help_text='Whether a DM was sent to the user when infraction was applied.', null=True),
        ),
    ]
