# Generated by Django 3.0.14 on 2021-11-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_infraction_dm_sent'),
        ('api', '0075_add_redirects_filter'),
    ]

    operations = [
    ]
