# Generated by Django 3.1.13 on 2021-11-27 12:27

import django.contrib.postgres.fields
from django.db import migrations, models
import pydis_site.apps.api.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_merge_20211125_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsetting',
            name='data',
            field=models.JSONField(help_text='The actual settings of this setting.'),
        ),
        migrations.AlterField(
            model_name='deletedmessage',
            name='embeds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[pydis_site.apps.api.models.utils.validate_embed]), blank=True, help_text='Embeds attached to this message.', size=None),
        ),
    ]
