# Generated by Django 3.1.14 on 2021-12-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_use_generic_jsonfield'),
        ('api', '0074_merge_20211105_0518'),
    ]

    operations = [
    ]
