# Generated by Django 3.1.14 on 2021-12-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_prepare_filter_and_filterlist_for_new_filter_schema'),
        ('api', '0077_use_generic_jsonfield'),
    ]

    operations = [
    ]
