# Generated by Django 3.1.14 on 2022-01-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_merge_20211213_0552'),
        ('api', '0074_voice_mute'),
    ]

    operations = [
    ]
