# Generated by Django 3.1.14 on 2022-03-06 16:07

from django.db import migrations, models
import django.db.models.deletion
import pydis_site.apps.api.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_merge_20220125_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='AocAccountLink',
            fields=[
                ('user', models.OneToOneField(help_text='The user that is blocked from getting the AoC Completionist Role', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('aoc_username', models.CharField(help_text='The AoC username associated with the Discord User.', max_length=120)),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AocCompletionistBlock',
            fields=[
                ('user', models.OneToOneField(help_text='The user that is blocked from getting the AoC Completionist Role', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('is_blocked', models.BooleanField(default=True, help_text='Whether this user is actively being blocked from getting the AoC Completionist Role', verbose_name='Blocked')),
                ('reason', models.TextField(help_text='The reason for the AoC Completionist Role Block.', null=True)),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
    ]
