# Generated by Django 3.1.14 on 2022-02-19 16:26

import django.core.validators
from django.db import migrations, models
import pydis_site.apps.api.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_add_aoc_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='BumpedThread',
            fields=[
                ('thread_id', models.BigIntegerField(help_text='The thread ID that should be bumped.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Thread IDs cannot be negative.')], verbose_name='Thread ID')),
            ],
            bases=(pydis_site.apps.api.models.mixins.ModelReprMixin, models.Model),
        ),
    ]
