# Generated by Django 4.0.6 on 2022-07-27 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_remove_embed_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='last_applied',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of when this infraction was last applied.'),
        ),
    ]
