# Generated by Django 4.1.2 on 2022-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_infraction_last_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='thread_id',
            field=models.BigIntegerField(blank=True, help_text="The nomination vote's thread id.", null=True),
        ),
    ]
