# Generated by Django 4.1.6 on 2023-02-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_add_thread_id_to_nominations'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='jump_url',
            field=models.CharField(default='', help_text='The jump url to message invoking the infraction.', max_length=88),
        ),
    ]
