# Generated by Django 5.0 on 2024-05-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_user_alts'),
        ('api', '0095_user_display_name'),
    ]

    operations = [
    ]
