# Generated by Django 2.1 on 2018-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeName',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scientific', models.CharField(max_length=150)),
            ],
        ),
    ]
