# Generated by Django 2.1 on 2018-08-31 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documentationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffTopicChannelName',
            fields=[
                ('name', models.CharField(max_length=96, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')])),
            ],
        ),
    ]
