# Generated by Django 2.1.1 on 2018-09-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this tag, displayed in the Embed.', max_length=256, unique=True)),
                ('content', models.CharField(help_text='The content of this tag, displayed in the Embed.', max_length=2048)),
                ('image_url', models.URLField(help_text='An optional image to display in the tag embed.', null=True)),
                ('thumbnail_url', models.URLField(help_text='An optional thumbnail to display in the tag embed.', null=True)),
                ('author', models.ForeignKey(help_text='The user that originally created this tag.', on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
    ]
