# Generated by Django 2.1.2 on 2018-10-19 16:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_snakefact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeIdiom',
            fields=[
                ('idiom', models.CharField(help_text='A snake idiom', max_length=140, primary_key=True, serialize=False)),
            ],
            bases=(api.models.ModelReprMixin, models.Model),
        ),
    ]
