# Generated by Django 2.1.2 on 2018-10-29 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181027_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsnake',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), help_text='Images displaying this special snake.', size=None),
        ),
    ]
