# Generated by Django 2.1.2 on 2018-11-25 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_snake_field_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsnake',
            name='name',
            field=models.CharField(help_text='A special snake name.', max_length=140, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^([^0-9])+$')]),
        ),
    ]
