# Generated by Django 2.1.5 on 2019-02-18 19:30

from django.db import migrations


def up(apps, schema_editor):
    BotSetting = apps.get_model('api', 'BotSetting')
    setting = BotSetting(
        name='defcon',
        data={
            'enabled': False,
            'days': 0
        }
    ).save()


def down(apps, schema_editor):  # pragma: no cover - not necessary to test
    BotSetting = apps.get_model('api', 'BotSetting')
    BotSetting.get(name='defcon').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_botsetting'),
    ]

    operations = [
        migrations.RunPython(up, down)
    ]
