FROM python:3.6-alpine3.7

RUN apk add --update tini
RUN apk add --update git
RUN apk add --update build-base
RUN apk add --update gcc
RUN apk add --update cmake

ENV PIPENV_VENV_IN_PROJECT=1
ENV PIPENV_IGNORE_VIRTUALENVS=1
ENV PIPENV_NOSPIN=1
ENV PIPENV_HIDE_EMOJIS=1

RUN pip install pipenv

RUN mkdir -p /site
COPY Pipfile /site
COPY Pipfile.lock /site
WORKDIR /site
ENV PYTHONPATH=/site

RUN pipenv sync
