# Generated by Django 4.0.6 on 2022-08-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date and time this data was last fetched.')),
                ('name', models.CharField(help_text="The tag's name.", max_length=50, primary_key=True, serialize=False)),
                ('body', models.TextField(help_text='The content of the tag.')),
                ('url', models.URLField(help_text='The URL to this tag on GitHub.')),
            ],
        ),
    ]
