# Generated by Django 4.0.6 on 2022-08-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='url',
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.CharField(help_text='The group the tag belongs to.', max_length=50, null=True),
        ),
    ]
