# Generated by Django 2.2 on 2019-04-16 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryMetadata',
            fields=[
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this data was last fetched.')),
                ('repo_name', models.CharField(help_text='The full name of the repo, e.g. python-discord/site', max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='The description of the repo.', max_length=400)),
                ('forks', models.IntegerField(help_text='The number of forks of this repo')),
                ('stargazers', models.IntegerField(help_text='The number of stargazers for this repo')),
                ('language', models.CharField(help_text='The primary programming language used for this repo.', max_length=20)),
            ],
        ),
    ]
