# Generated by Django 3.0.11 on 2020-12-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorymetadata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this data was last fetched.'),
        ),
    ]
