# Generated by Django 2.1.2 on 2018-10-11 14:25

import pysite.apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tag_embed_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeFact',
            fields=[
                ('fact', models.CharField(help_text='A fact about snakes.', max_length=200, primary_key=True, serialize=False)),
            ],
            bases=(pysite.apps.api.models.ModelReprMixin, models.Model),
        ),
    ]
