# Generated by Django 2.1.1 on 2018-11-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_snake_field_validators'),
        ('api', '0019_deletedmessage'),
    ]

    operations = [
    ]
