# Generated by Django 2.1.5 on 2019-01-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_use_proper_default_for_infraction_insertion_date'),
        ('api', '0021_merge_20181125_1015'),
    ]

    operations = [
    ]
