# Generated by Django 2.2.6 on 2019-10-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemapping',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Whether this role mapping relates to a Django staff group'),
        ),
    ]
