# Generated by Django 3.0.9 on 2020-10-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_add_is_staff_to_role_mappings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleMapping',
        ),
    ]
