name: Create Sentry release

on:
  workflow_call

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create a Sentry.io release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: python-discord
          SENTRY_PROJECT: site
        with:
          environment: production
          version_prefix: site@
