name: Create Sentry release

on:
  workflow_call

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Create a Sentry.io release
        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: python-discord
          SENTRY_PROJECT: site
        with:
          environment: production
          version_prefix: site@
