name: Build & Publish Static Preview

on:
  workflow_call:
    inputs:
      sha-tag:
        description: "A short-form SHA tag for the commit that triggered this workflow"
        required: true
        type: string

jobs:
  build:
    name: Build Static Preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Login to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the container, including an inline cache manifest to
      # allow us to use the registry as a cache source.
      - name: Build Docker Image (Main)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/python-discord/static-site:latest
          cache-to: type=inline
          tags: |
            ghcr.io/python-discord/static-site:latest
            ghcr.io/python-discord/static-site:${{ inputs.sha-tag }}
          build-args: |
            git_sha=${{ github.sha }}
            STATIC_BUILD=TRUE

      - name: Extract Build From Docker Image (Main)
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir docker_build \
          && docker run --entrypoint /bin/echo --name site \
          ghcr.io/python-discord/static-site:${INPUTS_SHA_TAG} \
          && docker cp site:/app docker_build/
        env:
          INPUTS_SHA_TAG: ${{ inputs.sha-tag }}

      # Build directly to a local folder
      - name: Build Docker Image (PR)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          push: false
          cache-from: type=registry,ref=ghcr.io/python-discord/static-site:latest
          outputs: type=local,dest=docker_build/
          build-args: |
            git_sha=${{ github.sha }}
            STATIC_BUILD=TRUE

      - name: Upload Build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: static-build
          path: docker_build/app/build/
          if-no-files-found: error
